version = 1
SPDX-PackageName = "material-components"
SPDX-PackageSupplier = "Slint Developers <info@slint.dev>"
SPDX-PackageDownloadLocation = "https://slint.dev/"

[[annotations]]
path = [
  "docs/public/favicon.svg",
  "docs/public/slint-logo-small-light.svg",
  "docs/public/slint-logo.woff",
  "docs/public/apple-touch-icon.png",
  "docs/public/favicon.ico",
  "docs/public/favicon-32x32.png",
  "docs/public/favicon-16x16.png",
  "docs/public/tablet-material.webp",
  "examples/gallery/frame-tablet.webp"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © SixtyFPS GmbH <info@slint.dev>"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = ["ui/icons/**.svg", "examples/gallery/ui/icons/**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Material Icons <https://github.com/material-icons/material-icons/blob/master/LICENSE>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "docs/**.json",
  "docs/src/assets/styles/**.css",
  "docs/src/assets/**.svg",
  "docs/src/content/docs/components/icons/**.svg",
  "docs/src/assets/**.webp",
  ".gitignore",
  "docs/pnpm-lock.yaml",
  "docs/src/assets/images/Components.png",
  "docs/src/assets/images/phone-dark.webp",
  "docs/src/assets/images/material-tablet.webp",
  "docs/src/assets/images/material-award.jpg",
  "docs/src/assets/images/material-design.jpg",
  "docs/src/config.yaml",
  "examples/gallery/ui/themes/**.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © SixtyFPS GmbH <info@slint.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "docs/src/assets/images/icons/**.svg",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2020-2024 Paweł Kuna <https://github.com/tabler/tabler-icons>"
SPDX-License-Identifier = "MIT"
