---
<!-- Copyright © SixtyFPS GmbH <info@slint.dev> ; SPDX-License-Identifier: MIT -->
title: DatePicker
description: DatePicker API.
---

import CodeSnippetMD from '/src/components/CodeSnippetMD.astro';
import SlintProperty from '/src/components/SlintProperty.astro';

<CodeSnippetMD imagePath="" noScreenShot scale="3" imageWidth="300" imageHeight="200" imageAlt="">
```slint
import { DatePicker } from "material.slint";
export component Example inherits Window {
    width: 400px;
    height: 300px;
    background: transparent;
    DatePicker {

    }
}
```
</CodeSnippetMD>

A `DatePicker` allows users to select a date  using a calendar interface or text input.
