// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { ComponentsView } from "components_view.slint";
import { Palette } from "std-widgets.slint";
import { MainWindowAdapter } from "../main_window_adapter.slint";
import { FilledIcons, OutlinedIcons } from "../icons.slint";
import {
    MaterialText,
    Typography,
    IconButton,
    MaterialPalette,
    Animations,
    NavigationRail,
    NavigationItem,
    NavigationBar,
    SmallAppBar,
    MaterialStyleMetrics
} from "../../../../material.slint";

export enum Views {
    components
}

export component MainView {
    property <Views> current_view: Views.components;
    property <[NavigationItem]> navigation_items: [
        {
            text: "Components",
            icon: OutlinedIcons.dashboard,
            icon_selected: FilledIcons.dashboard
        }
    ];

    VerticalLayout {
        app-bar := SmallAppBar {
            title: "Material 3";
            trailing_icons: [
                { icon: Palette.color_scheme == ColorScheme.light ? OutlinedIcons.dark_mode : OutlinedIcons.light_mode, enabled: true },
            ];
            container_background: MainWindowAdapter.container_background;

            trailing_clicked(index) => {
                if Palette.color_scheme == ColorScheme.light {
                    Palette.color_scheme = ColorScheme.dark;
                    return;
                }

                Palette.color_scheme = ColorScheme.light;
            }
        }

        Rectangle {
            background: MaterialPalette.background;

            if !MainWindowAdapter.break_layout : HorizontalLayout {
                // TODO: Add back when missing items for 1.0 are resolved
                //  NavigationRail {
                //      items: root.navigation_items;
                //  }


                if root.current_view == Views.components : ComponentsView {
                    horizontal_stretch: 1;
                }
            }

            if MainWindowAdapter.break_layout : VerticalLayout {
                if root.current_view == Views.components : ComponentsView {
                    horizontal_stretch: 1;
                }

                // TODO: Add back when missing items for 1.0 are resolved
                // NavigationBar {
                //     items: root.navigation_items;
                // }
            }
        }
    }


    Image {
        x: app-bar.x + (app-bar.width - self.width)/2;
        y: app-bar.y + (app-bar.height - self.height)/2;
        height: app-bar.height - 4 * MaterialStyleMetrics.padding_8;
        source: Palette.color_scheme == ColorScheme.light ? @image-url("../slint-logo-full-light.svg") : @image-url("../slint-logo-full-dark.svg");
        TouchArea {
            clicked => { MainWindowAdapter.open-url("https://slint.dev"); }
            mouse-cursor: MouseCursor.pointer;
        }
    }
}
