# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

name: Build, test and deploy docs

on:
  push:
    branches: [master, "feature/*"]
  pull_request:
    branches: [master, "feature/*"]
  workflow_run:
    workflows: ["autofix.ci"]
    types:
      - completed

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      deploy: ${{ steps.filter.outputs.deploy }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            deploy:
              - 'docs/**'

  deploy:
    if: ${{ needs.changes.outputs.deploy == 'true' && github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: [changes]
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.12.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs/dist --project-name=materialui
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}